/**
 * Typed lookup over `rbm-skins-index.json`, generated by
 * `scripts/extract-rbm-skins.py` from the JPEG panel-art resources embedded
 * in `.rbm` mods. Only mods the script has processed appear here — most of
 * the 367-mod corpus has no entry yet (see the script's `--all` mode).
 */

import rbmSkinsIndex from './rbm-skins-index.json';
import { normalizeBase } from '../lib/url';

/** One extracted skin image, already copied into `public/archive/rbm-skins/`. */
export interface ModSkinImage {
  /** Filename inside the mod's skin directory, e.g. `"Splash.jpg"`. */
  file: string;
  bytes: number;
  sha256: string;
}

/** All extracted skins for one `.rbm` mod. */
export interface ModSkinEntry {
  /** Directory under `public/archive/rbm-skins/` (slugified mod stem). */
  slug: string;
  /** Filename of the best representative image (splash screen when present). */
  primary: string;
  skins: ModSkinImage[];
}

interface RbmSkinsIndexFile {
  meta: { generated?: string; count?: number };
  mods: Record<string, ModSkinEntry>;
}

const skinsIndex = rbmSkinsIndex as RbmSkinsIndexFile;

const base = normalizeBase(import.meta.env.BASE_URL);
const SKINS_PREFIX = `${base}/archive/rbm-skins`;

/** Look up extracted skins for a mod by its `.rbm` filename (case-sensitive, matches mods-full-index.json). */
export function getModSkins(filename: string): ModSkinEntry | undefined {
  return skinsIndex.mods[filename];
}

/** Build the public URL for one skin image of a mod, or undefined when none was extracted. */
export function getModSkinUrl(filename: string, image?: string): string | undefined {
  const entry = getModSkins(filename);
  if (!entry) return undefined;
  const file = image ?? entry.primary;
  return `${SKINS_PREFIX}/${encodeURIComponent(entry.slug)}/${encodeURIComponent(file)}`;
}

/** All skin image URLs for a mod, in the same order as the index (primary first when marked). */
export function getModSkinUrls(filename: string): string[] {
  const entry = getModSkins(filename);
  if (!entry) return [];
  return entry.skins.map(
    (s) => `${SKINS_PREFIX}/${encodeURIComponent(entry.slug)}/${encodeURIComponent(s.file)}`
  );
}

export const skinnedModFilenames: string[] = Object.keys(skinsIndex.mods);
